name = "navsphere-pathos"
compatibility_date = "2025-07-26"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liFcM3813H9NiCUp"
GITHUB_OWNER = "pathosd"
GITHUB_REPO = "navsphere-pathos"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "http://pathos.cn"
NEXT_PUBLIC_API_URL="https://dh.leti.ltd"

